#!/usr/bin/env bash
source /path/to/env.sh

if [ -z "$1" ]; then
  echo "Error: Directory argument is empty"
elif [ ! -d "$1" ]; then
  echo "Error: Directory $1 does not exist"
else
  echo "Cleaning directory: $1"
  find "$1" -mindepth 1 -maxdepth 1 ! -name '.githolder' -exec rm -rf {} +
  touch "$1/.githolder"
fi
