#!/usr/bin/env bash
# helper function for `clean`, though can be called directly

# Check if required variables are set
if [ -z "$ANTLR_GRAMMAR_LIST" ] || [ -z "$ANTLR_OUT_DIR" ]; then
  echo "Error: Required environment variables ANTLR_GRAMMAR_LIST and ANTLR_OUT_DIR are not set."
  exit 1
fi

# Function to delete a specific grammar
delete_grammar() {
  local grammar=$1
  # echo "Attempting to delete grammar: $grammar"
  if [ -z "$grammar" ]; then
    echo "Error: Grammar name is empty"
  elif echo "$ANTLR_GRAMMAR_LIST" | grep -qw "$grammar"; then
    rm -f "$ANTLR_OUT_DIR/$grammar"*
    echo "Deleted files starting with $grammar in $ANTLR_OUT_DIR"
  else
    echo "Invalid grammar name: $grammar"
  fi
}

# If no argument is given, delete all grammars
if [ -z "$1" ]; then
  echo "Cleaning all grammar builds."
  for grammar in $ANTLR_GRAMMAR_LIST; do
    delete_grammar "$grammar"
  done
else
  echo "Argument provided: $1"
  delete_grammar "$1"
fi
