#!/usr/bin/env bash
# helper function for `clean`, though can be called directly

# Check if required variables are set
if [ -z "${EXECUTOR_IN_FPL}" ] || [ -z "${EXECUTOR_IN_DIR}" ]; then
  echo "Error: Required environment variables EXECUTOR_IN_FPL and EXECUTOR_IN_DIR are not set."
  exit 1
fi

# Function to delete a specific program
delete_program() {
  local program=$1
  # echo "Attempting to delete program: $program"
  if [ -z "$program" ]; then
    echo "Error: Program name is empty"
  elif echo "$ANTLR_PROGRAM_LIST" | grep -qw "$program"; then
    rm -f "$ANTLR_OUT_DIR/$program"*
    echo "Deleted files starting with $program in $ANTLR_OUT_DIR"
  else
    echo "Invalid program name: $program"
  fi
}

# If no argument is given, delete all programs
if [ -z "$1" ]; then
  echo "removing all program and their jars."
  for program in ${EXECUTOR_IN_FPL}; do
    delete_program "$program"
  done
else
  echo "rmoving program $1 and its jar."
  delete_program "$1"
fi
