#!/usr/bin/env bash

# Check if REPO_HOME is set, if not exit with an error
if [ -z "$REPO_HOME" ]; then
  echo "REPO_HOME is not set. Please initialize the environment."
  exit 1
fi

# Function to handle errors
handle_error() {
  echo "Error occurred during ANTLR cleanup. Exiting."
  exit 1
}

# Clean the ANTLR directory
antlr_dir=$(find "$REPO_HOME/tool" -maxdepth 1 -type d -name "antlr4-*" | head -n 1)
if [ -n "$antlr_dir" ]; then
  find "$antlr_dir" -mindepth 1 -maxdepth 1 -not -type l -exec rm -rf {} + || handle_error
  find "$antlr_dir" -maxdepth 1 -type l -exec rm -f {} + || handle_error
else
  echo "ANTLR directory does not exist."
fi

echo "ANTLR cleanup complete."
