#!/usr/bin/env bash

# Check if REPO_HOME is set, if not exit with an error
if [ -z "$REPO_HOME" ]; then
  echo "REPO_HOME is not set. Please initialize the environment."
  exit 1
fi

# Function to handle errors
handle_error() {
  echo "Error occurred during Java cleanup. Exiting."
  exit 1
}

# Clean the JDK directory
jdk_dir=$(find "$REPO_HOME/toolsmiths" -maxdepth 1 -type d -name "jdk-*" | head -n 1)
if [ -n "$jdk_dir" ]; then
  find "$jdk_dir" -mindepth 1 -maxdepth 1 -not -type l -exec rm -rf {} + || handle_error
  find "$jdk_dir" -maxdepth 1 -type l -exec rm -f {} + || handle_error
else
  echo "JDK directory does not exist."
fi

echo "Java cleanup complete."
