#!/usr/bin/env bash

script_path="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
export PROJECT=$(basename "$script_path")
export PATH="$script_path"/env/bin:$PATH

# Set environment variables for ANTLR
export CLASSPATH=".:$script_path/env/antlr-4.9.2-complete.jar:$CLASSPATH"
export PATH="$PATH:$script_path/env"

cd development
