#!/usr/bin/env bash

script_path="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
project_root="${script_path%/*}"
export PROJECT=$(basename "$project_root")

# Set PATH to include tool/executor
export PATH="$project_root/tool/executor:$PATH"

# Set environment variables for ANTLR
export CLASSPATH=".:$project_root/tool/executor/antlr-4.9.2-complete.jar:$CLASSPATH"

alias ls="ls -a"
cd "$project_root/developer"
